export enum REPORT_SUMMARY_TYPE {
  DAILY_INVEST_REPORT_SUMMARY = "DAILY_INVEST_REPORT_SUMMARY",
  DAILY_DEBENTURE_REPORT_SUMMARY = "DAILY_DEBENTURE_REPORT_SUMMARY",
  DAILY_ECONOMY_REPORT_SUMMARY = "DAILY_ECONOMY_REPORT_SUMMARY",
  DAILY_STOCK_REPORT_SUMMARY = "DAILY_STOCK_REPORT_SUMMARY",
  DAILY_INDUSTRY_REPORT_SUMMARY = "DAILY_INDUSTRY_REPORT_SUMMARY",
  DAILY_MARKET_INFO_REPORT_SUMMARY = "DAILY_MARKET_INFO_REPORT_SUMMARY",
}
